/**
 * Platinum+ Wiki — Client-Side Router (History API)
 * Transforms the wiki into a SPA with real URLs compatible with Cloudflare Pages.
 */

(function() {
    'use strict';

    // ============================================================
    // 1. ROUTE MAP — maps URL paths to page IDs
    // ============================================================
    const ROUTES = {
        '/hardware/optimize-core-scheduling': { pageId: 'optimize-core-scheduling', category: 'HARDWARE', title: 'Optimize Core Scheduling' },
        '/hardware/optimize-task-profiles': { pageId: 'optimize-task-profiles', category: 'HARDWARE', title: 'Optimize Task Profiles' },
        '/system/optimize-kernel-timer-scheduling': { pageId: 'optimize-kernel-timer-scheduling', category: 'SYSTEM', title: 'Optimize Kernel Timer Scheduling' },
        '/system/optimize-priority-separation': { pageId: 'optimize-priority-separation', category: 'SYSTEM', title: 'Optimize Priority Separation' },
        '/hardware/optimize-dwm-gpu-scheduling': { pageId: 'optimize-dwm-gpu-scheduling', category: 'HARDWARE', title: 'Optimize DWM GPU Scheduling' },
        '/hardware/optimize-optimize-dwm-rendering': { pageId: 'optimize-optimize-dwm-rendering', category: 'HARDWARE', title: 'Optimize: Optimize DWM Rendering' },
        '/hardware/optimize-dwm-ink-timing': { pageId: 'optimize-dwm-ink-timing', category: 'HARDWARE', title: 'Optimize DWM Ink Timing' },
        '/hardware/disable-wpf-graphics': { pageId: 'disable-wpf-graphics', category: 'HARDWARE', title: 'Disable WPF Graphics' },
        '/system/optimize-kernel-scheduling': { pageId: 'optimize-kernel-scheduling', category: 'SYSTEM', title: 'Optimize Kernel Scheduling' },
        '/hardware/optimize-memory-management': { pageId: 'optimize-memory-management', category: 'HARDWARE', title: 'Optimize Memory Management' },
        '/system/optimize-executive-power-policies': { pageId: 'optimize-executive-power-policies', category: 'SYSTEM', title: 'Optimize Executive & Power Policies' },
        '/system/optimize-session-manager': { pageId: 'optimize-session-manager', category: 'SYSTEM', title: 'Optimize Session Manager' },
        '/hardware/optimize-game-mode-gpu-scheduling': { pageId: 'optimize-game-mode-gpu-scheduling', category: 'HARDWARE', title: 'Optimize Game Mode GPU Scheduling' },
        '/hardware/optimize-dxg-graphics-management': { pageId: 'optimize-dxg-graphics-management', category: 'HARDWARE', title: 'Optimize DXG Graphics Management' },
        '/system/optimize-dxg-kernel-scheduler': { pageId: 'optimize-dxg-kernel-scheduler', category: 'SYSTEM', title: 'Optimize DXG Kernel Scheduler' },
        '/hardware/optimize-dxg-memory-management': { pageId: 'optimize-dxg-memory-management', category: 'HARDWARE', title: 'Optimize DXG Memory Management' },
        '/hardware/optimize-dxg-display-configurations': { pageId: 'optimize-dxg-display-configurations', category: 'HARDWARE', title: 'Optimize DXG Display Configurations' },
        '/hardware/optimize-hardware-gpu-scheduling': { pageId: 'optimize-hardware-gpu-scheduling', category: 'HARDWARE', title: 'Optimize Hardware GPU Scheduling' },
        '/hardware/optimize-heap-memory-management': { pageId: 'optimize-heap-memory-management', category: 'HARDWARE', title: 'Optimize Heap Memory Management' },
        '/system/disable-dwm-heap-logging': { pageId: 'disable-dwm-heap-logging', category: 'SYSTEM', title: 'Disable DWM Heap Logging' },
        '/system/disable-telemetry-data-collection': { pageId: 'disable-telemetry-data-collection', category: 'SYSTEM', title: 'Disable Telemetry & Data Collection' },
        '/system/disable-error-reporting-and-diagnostics': { pageId: 'disable-error-reporting-and-diagnostics', category: 'SYSTEM', title: 'Disable Error Reporting and Diagnostics' },
        '/system/disable-background-maintenance': { pageId: 'disable-background-maintenance', category: 'SYSTEM', title: 'Disable Background Maintenance' },
        '/system/disable-automated-update-services': { pageId: 'disable-automated-update-services', category: 'SYSTEM', title: 'Disable Automated Update Services' },
        '/additional/disable-network-wi-fi-and-location-polling': { pageId: 'disable-network-wi-fi-and-location-polling', category: 'ADDITIONAL', title: 'Disable Network, Wi-Fi, and Location Polling' },
        '/system/disable-peripheral-printing-and-accessory-tasks': { pageId: 'disable-peripheral-printing-and-accessory-tasks', category: 'SYSTEM', title: 'Disable Peripheral, Printing, and Accessory Tasks' },
        '/system/disable-third-party-and-ai-telemetry': { pageId: 'disable-third-party-and-ai-telemetry', category: 'SYSTEM', title: 'Disable Third-Party and AI Telemetry' },
        '/system/disable-localization-and-time-synchronization-tasks': { pageId: 'disable-localization-and-time-synchronization-tasks', category: 'SYSTEM', title: 'Disable Localization and Time Synchronization Tasks' },
        '/system/disable-security-account-and-power-diagnostics': { pageId: 'disable-security-account-and-power-diagnostics', category: 'SYSTEM', title: 'Disable Security, Account, and Power Diagnostics' },
        '/system/disable-system-core-telemetry-and-diagnostics': { pageId: 'disable-system-core-telemetry-and-diagnostics', category: 'SYSTEM', title: 'Disable System Core Telemetry and Diagnostics' },
        '/system/disable-system-maintenance-and-background-activity': { pageId: 'disable-system-maintenance-and-background-activity', category: 'SYSTEM', title: 'Disable System Maintenance and Background Activity' },
        '/system/disable-windows-update-store-and-edge-services': { pageId: 'disable-windows-update-store-and-edge-services', category: 'SYSTEM', title: 'Disable Windows Update, Store, and Edge Services' },
        '/system/disable-network-discovery-and-file-sharing-services': { pageId: 'disable-network-discovery-and-file-sharing-services', category: 'SYSTEM', title: 'Disable Network Discovery and File Sharing Services' },
        '/system/disable-virtualization-and-hyper-v-services': { pageId: 'disable-virtualization-and-hyper-v-services', category: 'SYSTEM', title: 'Disable Virtualization and Hyper-V Services' },
        '/system/disable-bluetooth-wi-fi-and-device-polling': { pageId: 'disable-bluetooth-wi-fi-and-device-polling', category: 'SYSTEM', title: 'Disable Bluetooth, Wi-Fi, and Device Polling' },
        '/system/disable-printing-imaging-and-legacy-hardware': { pageId: 'disable-printing-imaging-and-legacy-hardware', category: 'SYSTEM', title: 'Disable Printing, Imaging, and Legacy Hardware' },
        '/system/disable-security-defender-and-authentication': { pageId: 'disable-security-defender-and-authentication', category: 'SYSTEM', title: 'Disable Security, Defender, and Authentication' },
        '/system/disable-remote-desktop-vpn-and-network-protocols': { pageId: 'disable-remote-desktop-vpn-and-network-protocols', category: 'SYSTEM', title: 'Disable Remote Desktop, VPN, and Network Protocols' },
        '/system/disable-gaming-xbox-and-peripheral-services': { pageId: 'disable-gaming-xbox-and-peripheral-services', category: 'SYSTEM', title: 'Disable Gaming, Xbox, and Peripheral Services' },
        '/system/disable-sensors-broadcasts-and-mixed-reality-services': { pageId: 'disable-sensors-broadcasts-and-mixed-reality-services', category: 'SYSTEM', title: 'Disable Sensors, Broadcasts, and Mixed Reality Services' },
        '/hardware/optimize-cpu-scheduling-apic-and-system-timers': { pageId: 'optimize-cpu-scheduling-apic-and-system-timers', category: 'HARDWARE', title: 'Optimize CPU Scheduling, APIC, and System Timers' },
        '/system/disable-virtualization-hypervisor-and-elam-overhead': { pageId: 'disable-virtualization-hypervisor-and-elam-overhead', category: 'SYSTEM', title: 'Disable Virtualization, Hypervisor, and ELAM Overhead' },
        '/system/optimize-boot-process-gui-rendering-and-recovery': { pageId: 'optimize-boot-process-gui-rendering-and-recovery', category: 'SYSTEM', title: 'Optimize Boot Process, GUI Rendering, and Recovery' },
        '/hardware/optimize-memory-management-pci-and-address-space': { pageId: 'optimize-memory-management-pci-and-address-space', category: 'HARDWARE', title: 'Optimize Memory Management, PCI, and Address Space' },
        '/system/disable-system-debugging-telemetry-and-diagnostics': { pageId: 'disable-system-debugging-telemetry-and-diagnostics', category: 'SYSTEM', title: 'Disable System Debugging, Telemetry, and Diagnostics' },
        '/additional/optimize-file-system-and-storage-i-o': { pageId: 'optimize-file-system-and-storage-i-o', category: 'ADDITIONAL', title: 'Optimize File System and Storage I/O' },
        '/system/disable-hyper-v-and-virtualization-services': { pageId: 'disable-hyper-v-and-virtualization-services', category: 'SYSTEM', title: 'Disable Hyper-V and Virtualization Services' },
        '/system/disable-search-indexing-and-web-integration': { pageId: 'disable-search-indexing-and-web-integration', category: 'SYSTEM', title: 'Disable Search Indexing and Web Integration' },
        '/system/disable-start-menu-tracking-and-app-notifications': { pageId: 'disable-start-menu-tracking-and-app-notifications', category: 'SYSTEM', title: 'Disable Start Menu Tracking and App Notifications' },
        '/system/optimize-process-termination-timeouts': { pageId: 'optimize-process-termination-timeouts', category: 'SYSTEM', title: 'Optimize Process Termination Timeouts' },
        '/hardware/enable-prefetcher-for-boot-and-application-startup': { pageId: 'enable-prefetcher-for-boot-and-application-startup', category: 'HARDWARE', title: 'Enable Prefetcher for Boot and Application Startup' },
        '/hardware/enable-superfetch-for-proactive-memory-management': { pageId: 'enable-superfetch-for-proactive-memory-management', category: 'HARDWARE', title: 'Enable Superfetch for Proactive Memory Management' },
        '/system/optimize-readyboot-and-prefetcher-integration': { pageId: 'optimize-readyboot-and-prefetcher-integration', category: 'SYSTEM', title: 'Optimize ReadyBoot and Prefetcher Integration' },
        '/additional/disable-raw-mouse-throttling': { pageId: 'disable-raw-mouse-throttling', category: 'ADDITIONAL', title: 'Disable Raw Mouse Throttling' },
        '/additional/disable-pointer-acceleration-for-mouse-subsystem': { pageId: 'disable-pointer-acceleration-for-mouse-subsystem', category: 'ADDITIONAL', title: 'Disable Pointer Acceleration for Mouse Subsystem' },
        '/additional/optimize-click-tolerances-for-mouse-subsystem': { pageId: 'optimize-click-tolerances-for-mouse-subsystem', category: 'ADDITIONAL', title: 'Optimize Click Tolerances for Mouse Subsystem' },
        '/additional/disable-edge-snapping-for-cursor-subsystem': { pageId: 'disable-edge-snapping-for-cursor-subsystem', category: 'ADDITIONAL', title: 'Disable Edge Snapping for Cursor Subsystem' },
        '/additional/optimize-wheel-routing-for-scrolling-subsystem': { pageId: 'optimize-wheel-routing-for-scrolling-subsystem', category: 'ADDITIONAL', title: 'Optimize Wheel Routing for Scrolling Subsystem' },
        '/additional/optimize-audio-engine-format-and-sample-rate': { pageId: 'optimize-audio-engine-format-and-sample-rate', category: 'ADDITIONAL', title: 'Optimize Audio Engine Format and Sample Rate' },
        '/additional/optimize-usb-transfer-and-controller-flags': { pageId: 'optimize-usb-transfer-and-controller-flags', category: 'ADDITIONAL', title: 'Optimize USB Transfer and Controller Flags' },
        '/additional/disable-usb-link-power-management-and-sleep-states': { pageId: 'disable-usb-link-power-management-and-sleep-states', category: 'ADDITIONAL', title: 'Disable USB Link Power Management and Sleep States' },
        '/additional/optimize-usb-descriptor-validation-and-enumeration': { pageId: 'optimize-usb-descriptor-validation-and-enumeration', category: 'ADDITIONAL', title: 'Optimize USB Descriptor Validation and Enumeration' },
        '/additional/disable-usb-error-recovery-and-hardware-hacks': { pageId: 'disable-usb-error-recovery-and-hardware-hacks', category: 'ADDITIONAL', title: 'Disable USB Error Recovery and Hardware Hacks' },
        '/system/disable-usb-telemetry-and-diagnostic-subsystems': { pageId: 'disable-usb-telemetry-and-diagnostic-subsystems', category: 'SYSTEM', title: 'Disable USB Telemetry and Diagnostic Subsystems' },
        '/additional/optimize-usb-power-management-and-suspend-states': { pageId: 'optimize-usb-power-management-and-suspend-states', category: 'ADDITIONAL', title: 'Optimize USB Power Management and Suspend States' },
        '/system/disable-usb-debugging-and-telemetry-logging': { pageId: 'disable-usb-debugging-and-telemetry-logging', category: 'SYSTEM', title: 'Disable USB Debugging and Telemetry Logging' },
        '/additional/optimize-usb-controller-bandwidth-and-direct-access': { pageId: 'optimize-usb-controller-bandwidth-and-direct-access', category: 'ADDITIONAL', title: 'Optimize USB Controller Bandwidth and Direct Access' },
        '/additional/optimize-usb-hub-power-management-and-resume-behavior': { pageId: 'optimize-usb-hub-power-management-and-resume-behavior', category: 'ADDITIONAL', title: 'Optimize USB Hub Power Management and Resume Behavior' },
        '/system/disable-usb-hub-diagnostics-and-debug-logging': { pageId: 'disable-usb-hub-diagnostics-and-debug-logging', category: 'SYSTEM', title: 'Disable USB Hub Diagnostics and Debug Logging' },
        '/system/disable-uxd-support-and-device-caching': { pageId: 'disable-uxd-support-and-device-caching', category: 'SYSTEM', title: 'Disable UXD Support and Device Caching' },
        '/additional/optimize-input-delay-and-layout-hotkeys': { pageId: 'optimize-input-delay-and-layout-hotkeys', category: 'ADDITIONAL', title: 'Optimize Input Delay and Layout Hotkeys' },
        '/additional/optimize-audio-engine-real-time-processing-and-threading': { pageId: 'optimize-audio-engine-real-time-processing-and-threading', category: 'ADDITIONAL', title: 'Optimize Audio Engine Real-Time Processing and Threading' },
        '/system/disable-audio-diagnostics-telemetry-and-watchdog-timers': { pageId: 'disable-audio-diagnostics-telemetry-and-watchdog-timers', category: 'SYSTEM', title: 'Disable Audio Diagnostics, Telemetry, and Watchdog Timers' },
        '/additional/disable-spatial-audio-ducking-and-third-party-enhancements': { pageId: 'disable-spatial-audio-ducking-and-third-party-enhancements', category: 'ADDITIONAL', title: 'Disable Spatial Audio, Ducking, and Third-Party Enhancements' },
        '/additional/disable-nvme-idle-power-states-and-resume-latency': { pageId: 'disable-nvme-idle-power-states-and-resume-latency', category: 'ADDITIONAL', title: 'Disable NVMe Idle Power States and Resume Latency' },
        '/additional/optimize-nvme-i-o-queues-polling-and-interrupt-coalescing': { pageId: 'optimize-nvme-i-o-queues-polling-and-interrupt-coalescing', category: 'ADDITIONAL', title: 'Optimize NVMe I/O Queues, Polling, and Interrupt Coalescing' },
        '/additional/disable-nvme-diagnostics-etw-telemetry-and-error-logging': { pageId: 'disable-nvme-diagnostics-etw-telemetry-and-error-logging', category: 'ADDITIONAL', title: 'Disable NVMe Diagnostics, ETW Telemetry, and Error Logging' },
        '/additional/disable-nvme-hardware-workarounds-and-compatibility-layers': { pageId: 'disable-nvme-hardware-workarounds-and-compatibility-layers', category: 'ADDITIONAL', title: 'Disable NVMe Hardware Workarounds and Compatibility Layers' },
        '/additional/optimize-directstorage-bypassio-and-dma-remapping': { pageId: 'optimize-directstorage-bypassio-and-dma-remapping', category: 'ADDITIONAL', title: 'Optimize DirectStorage BypassIO and DMA Remapping' },
        '/additional/disable-storport-telemetry-etw-logging-and-diagnostics': { pageId: 'disable-storport-telemetry-etw-logging-and-diagnostics', category: 'ADDITIONAL', title: 'Disable StorPort Telemetry, ETW Logging, and Diagnostics' },
        '/additional/disable-storport-power-management-and-modern-standby': { pageId: 'disable-storport-power-management-and-modern-standby', category: 'ADDITIONAL', title: 'Disable StorPort Power Management and Modern Standby' },
        '/additional/optimize-storport-i-o-queues-dpc-and-hardware-processing': { pageId: 'optimize-storport-i-o-queues-dpc-and-hardware-processing', category: 'ADDITIONAL', title: 'Optimize StorPort I/O Queues, DPC, and Hardware Processing' },
        '/additional/disable-touch-pen-and-tablet-ui-features': { pageId: 'disable-touch-pen-and-tablet-ui-features', category: 'ADDITIONAL', title: 'Disable Touch, Pen, and Tablet UI Features' },
        '/additional/optimize-precision-touchpad-for-lowest-latency': { pageId: 'optimize-precision-touchpad-for-lowest-latency', category: 'ADDITIONAL', title: 'Optimize Precision Touchpad for Lowest Latency' },
        '/additional/disable-hardware-touch-screen-interface': { pageId: 'disable-hardware-touch-screen-interface', category: 'ADDITIONAL', title: 'Disable Hardware Touch Screen Interface' },
        '/system/disable-bluetooth-subsystem-and-services': { pageId: 'disable-bluetooth-subsystem-and-services', category: 'SYSTEM', title: 'Disable Bluetooth Subsystem and Services' },
        '/additional/disable-wake-on-input-and-connected-standby-triggers': { pageId: 'disable-wake-on-input-and-connected-standby-triggers', category: 'ADDITIONAL', title: 'Disable Wake on Input and Connected Standby Triggers' },
        '/system/disable-printer-services-for-system-environment': { pageId: 'disable-printer-services-for-system-environment', category: 'SYSTEM', title: 'Disable Printer Services for System Environment' },
        '/system/optimize-context-menu-for-windows-shell': { pageId: 'optimize-context-menu-for-windows-shell', category: 'SYSTEM', title: 'Optimize Context Menu for Windows Shell' },
        '/system/disable-printer-policies-for-windows': { pageId: 'disable-printer-policies-for-windows', category: 'SYSTEM', title: 'Disable Printer Policies for Windows' },
        '/additional/optimize-xhci-imod-for-usb-controllers': { pageId: 'optimize-xhci-imod-for-usb-controllers', category: 'ADDITIONAL', title: 'Optimize xHCI IMOD for USB Controllers' },
        '/hardware/disable-timer-coalescing-for-cpu-scheduling': { pageId: 'disable-timer-coalescing-for-cpu-scheduling', category: 'HARDWARE', title: 'Disable Timer Coalescing for CPU Scheduling' },
        '/additional/disable-selective-suspend-and-idle-states-for-usb-pnp-devices': { pageId: 'disable-selective-suspend-and-idle-states-for-usb-pnp-devices', category: 'ADDITIONAL', title: 'Disable Selective Suspend and Idle States for USB & PnP Devices' },
        '/hardware/optimize-pcie-and-bus-power-states': { pageId: 'optimize-pcie-and-bus-power-states', category: 'HARDWARE', title: 'Optimize PCIe and Bus Power States' },
        '/hardware/optimize-interrupt-management-and-affinity-policy': { pageId: 'optimize-interrupt-management-and-affinity-policy', category: 'HARDWARE', title: 'Optimize Interrupt Management and Affinity Policy' },
        '/additional/disable-storport-idle-power-management': { pageId: 'disable-storport-idle-power-management', category: 'ADDITIONAL', title: 'Disable StorPort Idle Power Management' },
        '/system/disable-system-sleep-hibernation-and-modern-standby': { pageId: 'disable-system-sleep-hibernation-and-modern-standby', category: 'SYSTEM', title: 'Disable System Sleep, Hibernation, and Modern Standby' },
        '/hardware/optimize-processor-power-management-and-disable-qos-throttling': { pageId: 'optimize-processor-power-management-and-disable-qos-throttling', category: 'HARDWARE', title: 'Optimize Processor Power Management and Disable QoS Throttling' },
        '/system/disable-power-telemetry-watchdogs-and-energy-estimators': { pageId: 'disable-power-telemetry-watchdogs-and-energy-estimators', category: 'SYSTEM', title: 'Disable Power Telemetry, Watchdogs, and Energy Estimators' },
        '/system/optimize-power-framework-pofx-hardware-timers-and-storage-d3': { pageId: 'optimize-power-framework-pofx-hardware-timers-and-storage-d3', category: 'SYSTEM', title: 'Optimize Power Framework (PoFx), Hardware Timers, and Storage D3' },
        '/additional/disable-usb-audio-idle-power-management-for-media-devices': { pageId: 'disable-usb-audio-idle-power-management-for-media-devices', category: 'ADDITIONAL', title: 'Disable USB Audio Idle Power Management for Media Devices' },
        '/additional/disable-power-savings-and-coalescing-for-network-adapters': { pageId: 'disable-power-savings-and-coalescing-for-network-adapters', category: 'ADDITIONAL', title: 'Disable Power Savings and Coalescing for Network Adapters' },
        '/system/disable-hibernation-fast-startup-and-boot-idle-states': { pageId: 'disable-hibernation-fast-startup-and-boot-idle-states', category: 'SYSTEM', title: 'Disable Hibernation, Fast Startup, and Boot Idle States' },
        '/system/disable-general-telemetry-and-diagnostic-data-collection': { pageId: 'disable-general-telemetry-and-diagnostic-data-collection', category: 'SYSTEM', title: 'Disable General Telemetry and Diagnostic Data Collection' },
        '/system/disable-windows-error-reporting-and-crash-dumps': { pageId: 'disable-windows-error-reporting-and-crash-dumps', category: 'SYSTEM', title: 'Disable Windows Error Reporting and Crash Dumps' },
        '/system/disable-suggestions-tips-and-windows-spotlight-for-ui': { pageId: 'disable-suggestions-tips-and-windows-spotlight-for-ui', category: 'SYSTEM', title: 'Disable Suggestions, Tips, and Windows Spotlight for UI' },
        '/additional/disable-automatic-map-downloads-for-network-subsystem': { pageId: 'disable-automatic-map-downloads-for-network-subsystem', category: 'ADDITIONAL', title: 'Disable Automatic Map Downloads for Network Subsystem' },
        '/system/disable-microsoft-copilot-and-ai-features-for-shell-subsystem': { pageId: 'disable-microsoft-copilot-and-ai-features-for-shell-subsystem', category: 'SYSTEM', title: 'Disable Microsoft Copilot and AI Features for Shell Subsystem' },
        '/system/disable-gamedvr-and-xbox-game-bar': { pageId: 'disable-gamedvr-and-xbox-game-bar', category: 'SYSTEM', title: 'Disable GameDVR and Xbox Game Bar' },
        '/system/optimize-startup-ets-event-trace-sessions': { pageId: 'optimize-startup-ets-event-trace-sessions', category: 'SYSTEM', title: 'Optimize Startup ETS (Event Trace Sessions)' },
        '/system/disable-wmplayer-telemetry-and-optimize-video-playback-for-media-subsystem': { pageId: 'disable-wmplayer-telemetry-and-optimize-video-playback-for-media-subsystem', category: 'SYSTEM', title: 'Disable WMPlayer Telemetry and Optimize Video Playback for Media Subsystem' },
        '/system/disable-cloud-and-telemetry-features-for-reduced-overhead': { pageId: 'disable-cloud-and-telemetry-features-for-reduced-overhead', category: 'SYSTEM', title: 'Disable Cloud and Telemetry Features for Reduced Overhead' },
        '/system/optimize-real-time-protection-settings-for-minimal-latency': { pageId: 'optimize-real-time-protection-settings-for-minimal-latency', category: 'SYSTEM', title: 'Optimize Real-Time Protection Settings for Minimal Latency' },
        '/system/disable-smartscreen-and-web-protection-features': { pageId: 'disable-smartscreen-and-web-protection-features', category: 'SYSTEM', title: 'Disable SmartScreen and Web Protection Features' },
        '/system/disable-notifications-and-privacy-intrusions': { pageId: 'disable-notifications-and-privacy-intrusions', category: 'SYSTEM', title: 'Disable Notifications and Privacy Intrusions' },
        '/system/disable-windows-update-and-background-servicing': { pageId: 'disable-windows-update-and-background-servicing', category: 'SYSTEM', title: 'Disable Windows Update and Background Servicing' },
        '/system/disable-system-exploit-mitigations-for-processor': { pageId: 'disable-system-exploit-mitigations-for-processor', category: 'SYSTEM', title: 'Disable System Exploit Mitigations for Processor' },
        '/hardware/disable-fault-tolerant-heap-for-memory-management': { pageId: 'disable-fault-tolerant-heap-for-memory-management', category: 'HARDWARE', title: 'Disable Fault-Tolerant Heap for Memory Management' },
        '/hardware/disable-dma-remapping-for-pcie-components': { pageId: 'disable-dma-remapping-for-pcie-components', category: 'HARDWARE', title: 'Disable DMA Remapping for PCIe Components' },
        '/hardware/optimize-gpu-timeout-detection-and-recovery-tdr': { pageId: 'optimize-gpu-timeout-detection-and-recovery-tdr', category: 'HARDWARE', title: 'Optimize GPU Timeout Detection and Recovery (TDR)' },
        '/hardware/disable-power-states-and-clock-slowdowns-for-nvidia-gpu': { pageId: 'disable-power-states-and-clock-slowdowns-for-nvidia-gpu', category: 'HARDWARE', title: 'Disable Power States and Clock Slowdowns for NVIDIA GPU' },
        '/hardware/optimize-profiling-and-telemetry-for-nvidia-gpu': { pageId: 'optimize-profiling-and-telemetry-for-nvidia-gpu', category: 'HARDWARE', title: 'Optimize Profiling and Telemetry for NVIDIA GPU' },
        '/hardware/optimize-nvidia-physx-and-performance-counters': { pageId: 'optimize-nvidia-physx-and-performance-counters', category: 'HARDWARE', title: 'Optimize NVIDIA PhysX and Performance Counters' },
        '/hardware/disable-video-processing-enhancements-for-nvidia-gpu': { pageId: 'disable-video-processing-enhancements-for-nvidia-gpu', category: 'HARDWARE', title: 'Disable Video Processing Enhancements for NVIDIA GPU' },
        '/hardware/optimize-display-database-and-monitor-configurations': { pageId: 'optimize-display-database-and-monitor-configurations', category: 'HARDWARE', title: 'Optimize Display Database and Monitor Configurations' },
        '/hardware/disable-telemetry-scheduled-tasks-for-nvidia-gpu': { pageId: 'disable-telemetry-scheduled-tasks-for-nvidia-gpu', category: 'HARDWARE', title: 'Disable Telemetry Scheduled Tasks for NVIDIA GPU' },
        '/hardware/disable-telemetry-and-data-collection-for-nvidia-gpu': { pageId: 'disable-telemetry-and-data-collection-for-nvidia-gpu', category: 'HARDWARE', title: 'Disable Telemetry and Data Collection for NVIDIA GPU' },
        '/hardware/disable-composition-and-post-processing-engines-for-gpu': { pageId: 'disable-composition-and-post-processing-engines-for-gpu', category: 'HARDWARE', title: 'Disable Composition and Post-Processing Engines for GPU' },
        '/hardware/optimize-variable-refresh-rate-vrr-for-gpu': { pageId: 'optimize-variable-refresh-rate-vrr-for-gpu', category: 'HARDWARE', title: 'Optimize Variable Refresh Rate (VRR) for GPU' },
        '/hardware/disable-workstation-and-stereo-3d-features-for-gpu': { pageId: 'disable-workstation-and-stereo-3d-features-for-gpu', category: 'HARDWARE', title: 'Disable Workstation and Stereo 3D Features for GPU' },
        '/hardware/optimize-multi-gpu-and-undocumented-extensions-for-gpu': { pageId: 'optimize-multi-gpu-and-undocumented-extensions-for-gpu', category: 'HARDWARE', title: 'Optimize Multi-GPU and Undocumented Extensions for GPU' },
        '/system/optimize-dxg-registry-references': { pageId: 'optimize-dxg-registry-references', category: 'SYSTEM', title: 'Optimize DXG Registry References' },
        '/hardware/intel-ppm-and-pep-tweak': { pageId: 'intel-ppm-and-pep-tweak', category: 'HARDWARE', title: 'Intel PPM & PEP Tweak' },
        '/hardware/amd-ppm-tweak': { pageId: 'amd-ppm-tweak', category: 'HARDWARE', title: 'AMD PPM Tweak' },
        '/additional/network-adapter-protocols-and-tcpip-optimization': { pageId: 'network-adapter-protocols-and-tcpip-optimization', category: 'ADDITIONAL', title: 'Network Adapter Protocols & TCP/IP Optimization' },
        '/hardware/nvidia-driver-optimization': { pageId: 'nvidia-driver-optimization', category: 'HARDWARE', title: 'NVIDIA Driver Optimization' },
        '/additional/base': { pageId: 'additional-base', category: 'Additional Tweaks', title: 'Coming soon...' },
        '/general/system-restore-point': { pageId: 'system-restore-point', category: 'GENERAL', title: 'System Restore Point' },
        '/general/registry-backup': { pageId: 'registry-backup', category: 'GENERAL', title: 'Registry Backup' },
        '/general/windows-fix': { pageId: 'windows-fix', category: 'GENERAL', title: 'Coming Soon...' },
        '/general/game-fix': { pageId: 'game-fix', category: 'GENERAL', title: 'Coming Soon...' },
        '/general/network-fix': { pageId: 'network-fix', category: 'GENERAL', title: 'Coming Soon...' },
        '/general/app-fix': { pageId: 'app-fix', category: 'GENERAL', title: 'Coming Soon...' },
        '/system/service-manager': { pageId: 'service-manager', category: 'SYSTEM', title: 'Service Manager' },
        '/additional/disable-network-discovery-and-file-sharing-services': { pageId: 'disable-network-discovery-and-file-sharing-services', category: 'ADDITIONAL', title: 'Disable Network Discovery and File Sharing Services' },
        '/additional/disable-bluetooth-wi-fi-and-device-polling': { pageId: 'disable-bluetooth-wi-fi-and-device-polling', category: 'ADDITIONAL', title: 'Disable Bluetooth, Wi-Fi, and Device Polling' },
        '/':                                    { pageId: 'welcome',             category: 'Introduction',       title: 'Welcome' },
        '/introduction':                        { pageId: 'welcome',             category: 'Introduction',       title: 'Welcome' },
        '/introduction/what-is-platinum':       { pageId: 'what-is-platinum',    category: 'Introduction',       title: '1.2 What is Platinum+' },
        '/introduction/how-to-use':             { pageId: 'how-to-use',          category: 'Introduction',       title: '1.3 How to use this Wiki' },
        '/introduction/disclaimer':             { pageId: 'disclaimer',          category: 'Introduction',       title: '1.4 Disclaimer' },
        '/introduction/about-me':               { pageId: 'about-me',            category: 'Introduction',       title: '1.5 About Us' },
        '/operating-system':                    { pageId: 'os-selection',        category: 'Operating System',   title: '2.1 OS Selection' },
        '/operating-system/os-selection':       { pageId: 'os-selection',        category: 'Operating System',   title: '2.1 OS Selection' },
        '/operating-system/system-preparation': { pageId: 'system-prep',         category: 'Operating System',   title: '2.1 System Preparation' },
        '/operating-system/windows-10-iso':     { pageId: 'install-iso-w10',     category: 'Operating System',   title: '2.2 Windows 10 ISO' },
        '/operating-system/windows-11-iso':     { pageId: 'install-iso-w11',     category: 'Operating System',   title: '2.2 Windows 11 ISO' },
        '/operating-system/partition-style':    { pageId: 'identify-partition-style', category: 'Operating System', title: '2.3 Identify Disk Partition Style (MBR/GPT)' },
        '/operating-system/rufus-installation': { pageId: 'rufus-installation',  category: 'Operating System',   title: '2.3 Rufus Installation' },
        '/operating-system/rufus-creation':     { pageId: 'rufus-creation',      category: 'Operating System',   title: '2.3 Rufus Setup and Bootable USB Creation' },
        '/operating-system/xml-customization':  { pageId: 'xml-customization',   category: 'Operating System',   title: '2.3 XML Customization (Unattended Setup)' },
        '/operating-system/boot-procedure':     { pageId: 'how-to-boot',         category: 'Operating System',   title: '2.4 USB Boot Procedure' },
        '/operating-system/windows-10-setup':   { pageId: 'setup-w10',           category: 'Operating System',   title: '2.4 Windows 10 Setup' },
        '/operating-system/windows-11-setup':   { pageId: 'setup-w11',           category: 'Operating System',   title: '2.4 Windows 11 Setup' },
        '/post-setup':                          { pageId: 'preos-network-configuration', category: 'Post-Setup OS', title: '3.1 Choose Connection Type' },
        '/post-setup/network-configuration':    { pageId: 'preos-network-configuration', category: 'Post-Setup OS', title: '3.1 Choose Connection Type' },
        '/post-setup/system-updates':           { pageId: 'preos-update-management',     category: 'Post-Setup OS', title: '3.2 System Updates' },
        '/post-setup/microsoft-account':        { pageId: 'preos-microsoft-account',     category: 'Post-Setup OS', title: '3.3 Microsoft Account' },
        '/post-setup/account-security':         { pageId: 'preos-account-security',      category: 'Post-Setup OS', title: '3.3 Account Security' },
        '/post-setup/windows-activation':       { pageId: 'preos-windows-activation',    category: 'Post-Setup OS', title: '3.3 Windows Activation' },
        '/drivers':                             { pageId: 'identify-hardware',   category: 'Drivers',           title: '4.1 Windows Update Driver Control' },
        '/drivers/driver-preparation':          { pageId: 'identify-hardware',   category: 'Drivers',           title: '4.1 Windows Update Driver Control' },
        '/drivers/clean-driver-ddu':            { pageId: 'clean-driver',        category: 'Drivers',           title: '4.1 Clean Driver (DDU)' },
        '/drivers/amd-chipset':                 { pageId: 'amd-chipset',         category: 'Drivers',           title: '4.2 AMD Chipset' },
        '/drivers/intel-chipset':               { pageId: 'intel-chipset',       category: 'Drivers',           title: '4.2 Intel Chipset' },
        '/drivers/amd-graphics':                { pageId: 'amd-gpu',             category: 'Drivers',           title: '4.3 AMD Graphics' },
        '/drivers/intel-graphics':              { pageId: 'intel-gpu',           category: 'Drivers',           title: '4.3 Intel Graphics' },
        '/drivers/nvidia-graphics':             { pageId: 'nvidia-gpu',          category: 'Drivers',           title: '4.3 Nvidia Graphics' },
        '/optimizations':                       { pageId: 'cpu-opt',             category: 'Optimizations',     title: '5.1 CPU Optimization' },
        '/optimizations/cpu':                   { pageId: 'cpu-opt',             category: 'Optimizations',     title: '5.1 CPU Optimization' },
        '/optimizations/gpu':                   { pageId: 'gpu-opt',             category: 'Optimizations',     title: '5.2 GPU Optimization' },
        '/optimizations/ram':                   { pageId: 'ram-opt',             category: 'Optimizations',     title: '5.3 RAM Management' },
        '/changelog':                           { pageId: 'v8.6',                category: 'Changelog',         title: '6.1 Version 8.6 Premium' },
        '/changelog/v8.6-premium':              { pageId: 'v8.6',                category: 'Changelog',         title: '6.1 Version 8.6 Premium' },
        '/changelog/v8.5-free':                 { pageId: 'v8.5',                category: 'Changelog',         title: '6.2 Version 8.5 Free' },
        '/test1':                               { pageId: 'test1',               category: 'Changelog',         title: '6.1 test1' },
        '/support/privacy-policy':              { pageId: 'privacy-policy',      category: 'Support',           title: '8.1 Privacy Policy' },
        '/support/legal-disclaimer':            { pageId: 'legal-disclaimer',    category: 'Support',           title: '8.2 Legal Disclaimer' },
};

    // ============================================================
    // 9. START ROUTER on DOMContentLoaded
    // ============================================================
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', initRouter);
    } else {
        initRouter();
    }

})();
