@echo off
title By Platinum+ Optimizer
reg add "HKCR\Applications\photoviewer.dll\shell\print" /f
reg add "HKCR\batfile\shell\print" /f
reg add "HKCR\cmdfile\shell\print" /f
reg add "HKCR\contact_wab_auto_file\shell\print" /f
reg add "HKCR\emffile\shell\print" /f
reg add "HKCR\fonfile\shell\print" /f
reg add "HKCR\group_wab_auto_file\shell\print" /f
reg add "HKCR\htmlfile\shell\print" /f
reg add "HKCR\IE.AssocFile.HTM\shell\print" /f
reg add "HKCR\IE.AssocFile.SVG\shell\print" /f
reg add "HKCR\IE.AssocFile.URL\shell\print" /f
reg add "HKCR\IE.AssocFile.XHT\shell\print" /f
reg add "HKCR\inffile\shell\print" /f
reg add "HKCR\inifile\shell\print" /f
reg add "HKCR\InternetShortcut\shell\print" /f
reg add "HKCR\JSEFile\shell\print" /f
reg add "HKCR\JSFile\shell\print" /f
reg add "HKCR\opensearchresult\shell\print" /f
reg add "HKCR\otffile\shell\print" /f
reg add "HKCR\PBrush\shell\print" /f
reg add "HKCR\pfmfile\shell\print" /f
reg add "HKCR\regfile\shell\print" /f
reg add "HKCR\rlefile\shell\print" /f
reg add "HKCR\svgfile\shell\print" /f
reg add "HKCR\SystemFileAssociations\.avci\shell\print" /f
reg add "HKCR\SystemFileAssociations\.avcs\shell\print" /f
reg add "HKCR\SystemFileAssociations\.avif\shell\print" /f
reg add "HKCR\SystemFileAssociations\.avifs\shell\print" /f
reg add "HKCR\SystemFileAssociations\.heic\shell\print" /f
reg add "HKCR\SystemFileAssociations\.heics\shell\print" /f
reg add "HKCR\SystemFileAssociations\.heif\shell\print" /f
reg add "HKCR\SystemFileAssociations\.heifs\shell\print" /f
reg add "HKCR\SystemFileAssociations\.hif\shell\print" /f
reg add "HKCR\SystemFileAssociations\.jxl\shell\print" /f
reg add "HKCR\SystemFileAssociations\image\shell\print" /f
reg add "HKCR\ttcfile\shell\print" /f
reg add "HKCR\ttffile\shell\print" /f
reg add "HKCR\txtfile\shell\print" /f
reg add "HKCR\VBEFile\shell\print" /f
reg add "HKCR\VBSFile\shell\print" /f
reg add "HKCR\wdpfile\shell\print" /f
reg add "HKCR\wmffile\shell\print" /f
reg add "HKCR\WSFFile\shell\print" /f
reg add "HKCR\xhtmlfile\shell\print" /f
reg add "HKCR\zapfile\shell\print" /f
echo.
echo Optimize Context Menu for Windows Shell restored successfully.
