@echo off
title By Platinum+ Optimizer
reg delete "HKCR\Applications\photoviewer.dll\shell\print" /f
reg delete "HKCR\batfile\shell\print" /f
reg delete "HKCR\cmdfile\shell\print" /f
reg delete "HKCR\contact_wab_auto_file\shell\print" /f
reg delete "HKCR\emffile\shell\print" /f
reg delete "HKCR\fonfile\shell\print" /f
reg delete "HKCR\group_wab_auto_file\shell\print" /f
reg delete "HKCR\htmlfile\shell\print" /f
reg delete "HKCR\IE.AssocFile.HTM\shell\print" /f
reg delete "HKCR\IE.AssocFile.SVG\shell\print" /f
reg delete "HKCR\IE.AssocFile.URL\shell\print" /f
reg delete "HKCR\IE.AssocFile.XHT\shell\print" /f
reg delete "HKCR\inffile\shell\print" /f
reg delete "HKCR\inifile\shell\print" /f
reg delete "HKCR\InternetShortcut\shell\print" /f
reg delete "HKCR\JSEFile\shell\print" /f
reg delete "HKCR\JSFile\shell\print" /f
reg delete "HKCR\opensearchresult\shell\print" /f
reg delete "HKCR\otffile\shell\print" /f
reg delete "HKCR\PBrush\shell\print" /f
reg delete "HKCR\pfmfile\shell\print" /f
reg delete "HKCR\regfile\shell\print" /f
reg delete "HKCR\rlefile\shell\print" /f
reg delete "HKCR\svgfile\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.avci\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.avcs\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.avif\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.avifs\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.heic\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.heics\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.heif\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.heifs\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.hif\shell\print" /f
reg delete "HKCR\SystemFileAssociations\.jxl\shell\print" /f
reg delete "HKCR\SystemFileAssociations\image\shell\print" /f
reg delete "HKCR\ttcfile\shell\print" /f
reg delete "HKCR\ttffile\shell\print" /f
reg delete "HKCR\txtfile\shell\print" /f
reg delete "HKCR\VBEFile\shell\print" /f
reg delete "HKCR\VBSFile\shell\print" /f
reg delete "HKCR\wdpfile\shell\print" /f
reg delete "HKCR\wmffile\shell\print" /f
reg delete "HKCR\WSFFile\shell\print" /f
reg delete "HKCR\xhtmlfile\shell\print" /f
reg delete "HKCR\zapfile\shell\print" /f
echo.
echo Optimize Context Menu for Windows Shell applied successfully.
